name: Snyk Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (required for Snyk)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Test Python dependencies
        run: snyk test --file=app/requirements.txt --package-manager=pip

      - name: Build Docker image
        run: docker build -t snyk-test-app ./app

      - name: Test Docker image for vulnerabilities
        run: snyk test --docker snyk-test-app
