name: Snyk Security Scan

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r app/requirements.txt

    - name: Install Snyk CLI
      run: |
        curl -sL https://snyk.io/install | bash
        echo "$HOME/.snyk" >> $GITHUB_PATH

    - name: Auth Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Snyk test (Python)
      run: snyk test --file=app/requirements.txt --command=python3

    - name: Snyk test (Docker)
      run: |
        docker build -t snyk-test-app ./app
        snyk test --docker snyk-test-app
